version: '3'

services:
  solr:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user_id:    ${USER_ID}
        user_name:  ${USER_NAME}
        group_id:   ${GROUP_ID}
        group_name: ${GROUP_NAME}
    volumes:
       - "${HOME}/mount_docker/data/solr/sample01:/opt/solr/server/solr/sample01/data"
       - "${HOME}/mount_docker/log/solr:/opt/solr/server/logs"
    ports:
      - "8983:8983"
    networks:
      - develop_nw
networks:
  develop_nw:
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.0/24
